# Generated by Django 5.2 on 2025-04-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='Student_file',
            field=models.ImageField(default='default.txt', upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitness',
            name='Student_plan',
            field=models.CharField(max_length=40),
        ),
    ]
