# Generated by Django 5.2 on 2025-05-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fitness_student_file_alter_fitness_student_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_contact', models.IntegerField()),
                ('stu_city', models.CharField(max_length=50)),
            ],
        ),
    ]
